#!/usr/bin/env bash
# Assemble .github/copilot-instructions.md for one review mode.
#
# Copilot code review reads its custom instructions from
# .github/copilot-instructions.md on the pull request's head branch, and from
# nowhere else. There is no per-run way to hand it a different prompt. So the
# review modes are stored here as fragments and composed into that one file:
# the checked-in copy is the `code` composition, which is what a human-opened
# pull request gets, and copilot-review.yml composes the other modes onto the
# scratch branches it opens.
#
#   ./compose.sh code            # write the composition to stdout
#   ./compose.sh --check code    # diff it against the checked-in file
#
# After editing any fragment, regenerate the checked-in file:
#
#   .github/review-modes/compose.sh code > .github/copilot-instructions.md

set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
target="$here/../copilot-instructions.md"

check=0
if [ "${1:-}" = "--check" ]; then
  check=1
  shift
fi

mode=${1:-code}
case "$mode" in
  code)     title="Code review";              parts=(common.md code.md) ;;
  security) title="Security review";          parts=(common.md security.md) ;;
  full)     title="Full review (code + security)"; parts=(common.md code.md security.md) ;;
  *)
    printf 'compose.sh: unknown mode %s (expected code, security or full)\n' "$mode" >&2
    exit 2
    ;;
esac

compose() {
  printf '<!-- Generated by .github/review-modes/compose.sh %s. Edit the fragments in\n' "$mode"
  printf '     .github/review-modes/, not this file. -->\n\n'
  printf '# Copilot review instructions — %s\n\n' "$title"

  case "$mode" in
    code)
      printf 'Review this change for defects: correctness, control flow, state handling,\n'
      printf 'concurrency, error paths, and API misuse. Security consequences are in scope\n'
      printf 'when you find them, but a bug does not need one to be worth reporting.\n'
      ;;
    security)
      printf 'Audit this change for security vulnerabilities. Report a defect only when you\n'
      printf 'can show a real attacker exploiting it against real users. Ordinary code\n'
      printf 'quality is not the subject of this review.\n'
      ;;
    full)
      printf 'Two reviews in one pass: the defect review described under **Code review**,\n'
      printf 'and the adversarial audit described under **Security review**. Cover both.\n'
      printf 'Report each defect exactly once — if a bug has a security consequence, make\n'
      printf 'that one comment a security finding rather than filing it twice.\n'
      ;;
  esac
  printf '\n'

  for part in "${parts[@]}"; do
    case "$part" in
      code.md)     printf '# Code review\n\n' ;;
      security.md) printf '# Security review\n\n' ;;
    esac
    cat "$here/$part"
    printf '\n'
  done
}

if [ "$check" = 1 ]; then
  if diff -u "$target" <(compose); then
    printf 'compose.sh: .github/copilot-instructions.md is up to date (%s)\n' "$mode"
  else
    printf '\ncompose.sh: .github/copilot-instructions.md is stale; regenerate with\n' >&2
    printf '  .github/review-modes/compose.sh %s > .github/copilot-instructions.md\n' "$mode" >&2
    exit 1
  fi
else
  compose
fi
